apiVersion: v1
kind: ServiceAccount
metadata:
  name: rancher-selector-sa
  namespace: kube-system

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rancher-selector-role
  namespace: kube-system
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create", "get", "update", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rancher-selector-rolebinding
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rancher-selector-role
subjects:
  - kind: ServiceAccount
    name: rancher-selector-sa
    namespace: kube-system

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rancher-selector
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rancher-selector
  template:
    metadata:
      labels:
        app: rancher-selector
    spec:
      serviceAccountName: rancher-selector-sa
      containers:
        - name: rancher-selector
          image: wrkode/rancher-selector:0.9
          imagePullPolicy: Always
---

apiVersion: v1
kind: Service
metadata:
  name: rancher-selector-service
  namespace: kube-system
spec:
  type: ClusterIP
  ports:
    - port: 8080
  selector:
    app: rancher-selector
